"""add join info

Revision ID: 091a7c82f8ae
Revises: df3506bc66b0
Create Date: 2018-06-17 10:19:17.638528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '091a7c82f8ae'
down_revision = 'df3506bc66b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('join_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('identity', sa.String(length=18), nullable=False),
    sa.ForeignKeyConstraint(['join_id'], ['join_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('join_activities', sa.Column('state', sa.Boolean(), nullable=True))
    op.drop_column('join_activities', 'paid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_activities', sa.Column('paid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('join_activities', 'state')
    op.drop_table('activity_contacts')
    # ### end Alembic commands ###
