"""add volunteer to user

Revision ID: 146b5312e515
Revises: b5e3ed6a938a
Create Date: 2018-07-29 16:47:17.829659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146b5312e515'
down_revision = 'b5e3ed6a938a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('volunteer', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'volunteer')
    # ### end Alembic commands ###
