"""modify team join activity

Revision ID: 1936b36be525
Revises: 2b7960c4a2d9
Create Date: 2018-08-02 19:50:21.433185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1936b36be525'
down_revision = '2b7960c4a2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('join_activities', 'team_content')
    op.add_column('team_join_activities', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('team_join_activities', sa.Column('team_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_join_activities', 'team_price')
    op.drop_column('team_join_activities', 'phone')
    op.add_column('join_activities', sa.Column('team_content', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
