"""add crowd funding + modify join 

Revision ID: 3851d6cea2c7
Revises: 9bb5e4977a63
Create Date: 2018-06-26 18:53:55.497844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3851d6cea2c7'
down_revision = '9bb5e4977a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crowd_funding_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('join_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['join_id'], ['join_activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('join_activities', sa.Column('crowd_funding_amount', sa.Integer(), nullable=True))
    op.add_column('join_activities', sa.Column('crowd_funding_number', sa.Integer(), nullable=True))
    op.add_column('join_activities', sa.Column('crowd_funding_text', sa.String(length=500), nullable=True))
    op.add_column('join_activities', sa.Column('payment', sa.Boolean(), nullable=True))
    op.add_column('join_activities', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('join_activities', 'price')
    op.drop_column('join_activities', 'payment')
    op.drop_column('join_activities', 'crowd_funding_text')
    op.drop_column('join_activities', 'crowd_funding_number')
    op.drop_column('join_activities', 'crowd_funding_amount')
    op.drop_table('crowd_funding_details')
    # ### end Alembic commands ###
