"""add body_html

Revision ID: 518a96361d73
Revises: ea18ff598b12
Create Date: 2018-06-05 21:41:12.597046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518a96361d73'
down_revision = 'ea18ff598b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('introduce_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'introduce_html')
    # ### end Alembic commands ###
