"""take PK of team_types off

Revision ID: 555f9ef57c1f
Revises: 8f43caf2eeba
Create Date: 2018-05-21 22:19:37.008400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '555f9ef57c1f'
down_revision = '8f43caf2eeba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_types', 'team_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('team_types', 'type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_types', 'type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('team_types', 'team_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
