"""add top with activity

Revision ID: 6cd2ed33f117
Revises: 9f96f9a08b27
Create Date: 2018-07-25 22:46:03.733950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd2ed33f117'
down_revision = '9f96f9a08b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('top', sa.Boolean(), nullable=True))
    op.add_column('activities', sa.Column('top_team', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'top_team')
    op.drop_column('activities', 'top')
    # ### end Alembic commands ###
