"""add leader column

Revision ID: 8f43caf2eeba
Revises: 24bbfed402a9
Create Date: 2018-05-20 16:53:59.655370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f43caf2eeba'
down_revision = '24bbfed402a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('leader_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['leader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'leader_id')
    # ### end Alembic commands ###
