"""add invest

Revision ID: 9adf93052c2d
Revises: d7607a1c8947
Create Date: 2018-08-03 06:05:37.101651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adf93052c2d'
down_revision = 'd7607a1c8947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=50), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('image', sa.String(length=1000), nullable=True),
    sa.Column('brand', sa.String(length=1000), nullable=True),
    sa.Column('product', sa.String(length=1000), nullable=True),
    sa.Column('market', sa.String(length=1000), nullable=True),
    sa.Column('other', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demands_company'), 'demands', ['company'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demands_company'), table_name='demands')
    op.drop_table('demands')
    # ### end Alembic commands ###
