"""add timestamp for ask

Revision ID: 9bb5e4977a63
Revises: 0374491d45e0
Create Date: 2018-06-23 09:25:37.370199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb5e4977a63'
down_revision = '0374491d45e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_questions', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_questions', 'timestamp')
    # ### end Alembic commands ###
