"""add admin function to team

Revision ID: 9f96f9a08b27
Revises: 992719a05bf2
Create Date: 2018-07-24 20:33:23.886750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f96f9a08b27'
down_revision = '992719a05bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_users', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('team_users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('team_users', sa.Column('title', sa.String(length=10), nullable=True))
    op.add_column('teams', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('teams', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('teams', sa.Column('document', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'document')
    op.drop_column('teams', 'disabled')
    op.drop_column('teams', 'approved')
    op.drop_column('team_users', 'title')
    op.drop_column('team_users', 'is_admin')
    op.drop_column('team_users', 'disabled')
    # ### end Alembic commands ###
