"""update team field

Revision ID: a51278937a0c
Revises: ffa551434061
Create Date: 2018-07-27 16:19:21.298799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51278937a0c'
down_revision = 'ffa551434061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('classify', sa.SmallInteger(), nullable=True))
    op.add_column('teams', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('teams', sa.Column('phone_show', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'phone_show')
    op.drop_column('teams', 'phone')
    op.drop_column('teams', 'classify')
    # ### end Alembic commands ###
