"""add Team_Users

Revision ID: aea56795a18d
Revises: 555f9ef57c1f
Create Date: 2018-05-23 22:47:43.134071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aea56795a18d'
down_revision = '555f9ef57c1f'
branch_labels = None
depends_on = None



def upgrade():	
	op.alter_column('team_types', 'team_id',
existing_type=mysql.INTEGER(display_width=11),
nullable=False)

	op.alter_column('team_types', 'type_id',
existing_type=mysql.INTEGER(display_width=11),nullable=False)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

	op.alter_column('team_types', 'type_id',
existing_type=mysql.INTEGER(display_width=11),nullable=False)

	op.alter_column('team_types', 'team_id',
existing_type=mysql.INTEGER(display_width=11),nullable=False)
      # ### end Alembic commands ###
