"""delete body_html

Revision ID: b0239f399c1d
Revises: 518a96361d73
Create Date: 2018-06-05 21:45:19.590174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0239f399c1d'
down_revision = '518a96361d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'introduce_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('introduce_html', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
