"""modify province

Revision ID: b5e3ed6a938a
Revises: a4d6a31c5ee2
Create Date: 2018-07-29 14:38:01.054997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5e3ed6a938a'
down_revision = 'a4d6a31c5ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_contacts', 'province')
    op.add_column('join_activities', sa.Column('province', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('join_activities', 'province')
    op.add_column('activity_contacts', sa.Column('province', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
