"""add team_content to Join

Revision ID: d755717690c3
Revises: 146b5312e515
Create Date: 2018-07-29 17:58:55.056446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd755717690c3'
down_revision = '146b5312e515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_activities', sa.Column('team_content', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('join_activities', 'team_content')
    # ### end Alembic commands ###
