"""add Activity

Revision ID: ea18ff598b12
Revises: aea56795a18d
Create Date: 2018-05-29 21:51:01.543448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea18ff598b12'
down_revision = 'aea56795a18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('belong_to_team', sa.Integer(), nullable=True),
    sa.Column('cover', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('days', sa.SmallInteger(), nullable=True),
    sa.Column('rally_site', sa.String(length=20), nullable=True),
    sa.Column('destination', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('maximum', sa.SmallInteger(), nullable=True),
    sa.Column('members', sa.SmallInteger(), nullable=True),
    sa.Column('price', sa.SmallInteger(), nullable=False),
    sa.Column('child_price', sa.SmallInteger(), nullable=True),
    sa.Column('intensity_index', sa.SmallInteger(), nullable=False),
    sa.Column('landscape_index', sa.SmallInteger(), nullable=False),
    sa.Column('introduce', sa.Text(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['belong_to_team'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_name'), 'activities', ['name'], unique=True)
    op.create_table('activity_types',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['outdoor_types.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_types')
    op.drop_index(op.f('ix_activities_name'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
